- name: Adding user with a name of roboshop
  ansible.builtin.user:
    name: roboshop

- name: Recursively remove app directory 
  ansible.builtin.file:
    path: /app
    state: absent # You're deploying a new version of a web app. You don’t want any old .jar, .log, or .tmp files left inside /app.

- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download {{component}} application"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: exact {{component}} application
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes